server.port=8080
spring.application.name=compound-compare

# Force UTF-8 encoding for HTTP responses and requests
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# SQLite datasource — compound.db is created/written by fetch_stocks.py
spring.datasource.url=jdbc:sqlite:data/compound.db
spring.datasource.driver-class-name=org.sqlite.JDBC
